spring.application.name=backEndPetx
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/ong_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=userdevtestjava@gmail.com
spring.mail.password=vbxobmwxhkujgtfb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

email.password-recover.token.minutes=30
email.password-recover.token.uri=http://localhost:3000/reset-password/

# Configuracoes do Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.messages.basename=messages
#spring.thymeleaf.cache=false

minio.url=http://localhost:9000
minio.access-key=12345678
minio.secret-key=12345678


server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


# ====== MinIO ======
minio.endpoint=http://localhost:9000
# minio.endpoint=http://minio:9000
# minio.endpoint=https://minio.seudominio.com

minio.accessKey=12345678
minio.secretKey=12345678
minio.bucket=ong
minio.presignSeconds=300

# Ambiente (só para montar o path dos objetos: petx/{env}/...)
app.env=dev

# Upload (tamanho máximo)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=200,expireAfterWrite=3m



## O que expor via HTTP (por padrão só health e info saem)
#management.endpoints.web.exposure.include=health,info,mappings
#management.health.mail.enabled=false
#
## (opcional) detalhes do health
#management.endpoint.health.show-details=always

# (opcional) trocar porta/base dos endpoints de actuator
# management.server.port=8083
# management.endpoints.web.base-path=/actuator   # default já é /actuator


spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true

# DevTools - Habilita hot reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=src/main/resources/templates,src/main/resources/static

# Cache - Desabilitar em desenvolvimento
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true

# Logging para debug
logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web=DEBUG
