--
-- PostgreSQL database dump
--


-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activity_log (
    entidade_id bigint,
    id bigint NOT NULL,
    ts timestamp(6) with time zone NOT NULL,
    mensagem character varying(1000),
    acao character varying(255) NOT NULL,
    entidade character varying(255) NOT NULL,
    usuario character varying(255),
    meta jsonb
);


--
-- Name: activity_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activity_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: animal_conjunto_tb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.animal_conjunto_tb (
    animal_conjunto_id bigint NOT NULL,
    animal_principal_id bigint NOT NULL,
    animal_relacionamento_id bigint NOT NULL
);


--
-- Name: animal_conjunto_tb_animal_conjunto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.animal_conjunto_tb ALTER COLUMN animal_conjunto_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.animal_conjunto_tb_animal_conjunto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: animal_doencas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.animal_doencas (
    animal_id bigint NOT NULL,
    doenca character varying(255)
);


--
-- Name: animal_doencas_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.animal_doencas_aud (
    rev integer NOT NULL,
    revtype smallint,
    animal_id bigint NOT NULL,
    doenca character varying(255) NOT NULL
);


--
-- Name: animal_tb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.animal_tb (
    arquivado boolean NOT NULL,
    quantidade_femeas integer,
    quantidade_machos integer,
    arquivado_em timestamp(6) with time zone,
    atualizado_em timestamp(6) without time zone NOT NULL,
    boletim_id bigint,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    id_ong bigint,
    arquivado_por character varying(100),
    motivo_arquivamento character varying(120),
    adotado character varying(255) NOT NULL,
    chip_id character varying(255),
    comportamento text,
    condicao_animal text,
    cor_pelagem character varying(255),
    especie character varying(255),
    imagem_principal_perfil text,
    maturidade character varying(255),
    nome character varying(255),
    origem character varying(255),
    porte character varying(255),
    raca character varying(255),
    saude character varying(255),
    sexo character varying(255),
    CONSTRAINT animal_tb_adotado_check CHECK (((adotado)::text = ANY ((ARRAY['DISPONIVEL'::character varying, 'ADOTADO'::character varying])::text[]))),
    CONSTRAINT animal_tb_especie_check CHECK (((especie)::text = ANY ((ARRAY['GATO'::character varying, 'CACHORRO'::character varying])::text[]))),
    CONSTRAINT animal_tb_maturidade_check CHECK (((maturidade)::text = ANY ((ARRAY['FILHOTE'::character varying, 'ADULTO'::character varying, 'IDOSO'::character varying])::text[]))),
    CONSTRAINT animal_tb_origem_check CHECK (((origem)::text = ANY ((ARRAY['GUARDA_MUNICIPAL'::character varying, 'ABANDONO'::character varying, 'RESGATE'::character varying, 'SMA'::character varying, 'DIRETORIA'::character varying, 'COMUNIDADE'::character varying, 'FUNCIONARIO'::character varying, 'PORTAO'::character varying, 'OUTROS'::character varying])::text[]))),
    CONSTRAINT animal_tb_porte_check CHECK (((porte)::text = ANY ((ARRAY['PEQUENO'::character varying, 'MEDIO'::character varying, 'GRANDE'::character varying])::text[]))),
    CONSTRAINT animal_tb_saude_check CHECK (((saude)::text = ANY ((ARRAY['DOENTE'::character varying, 'SAUDAVEL'::character varying])::text[]))),
    CONSTRAINT animal_tb_sexo_check CHECK (((sexo)::text = ANY ((ARRAY['MACHO'::character varying, 'FEMEA'::character varying])::text[])))
);


--
-- Name: animal_tb_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.animal_tb_aud (
    arquivado boolean,
    quantidade_femeas integer,
    quantidade_machos integer,
    rev integer NOT NULL,
    revtype smallint,
    arquivado_em timestamp(6) with time zone,
    boletim_id bigint,
    id bigint NOT NULL,
    id_ong bigint,
    arquivado_por character varying(100),
    motivo_arquivamento character varying(120),
    adotado character varying(255),
    chip_id character varying(255),
    comportamento text,
    condicao_animal text,
    cor_pelagem character varying(255),
    especie character varying(255),
    imagem_principal_perfil text,
    maturidade character varying(255),
    nome character varying(255),
    origem character varying(255),
    porte character varying(255),
    raca character varying(255),
    saude character varying(255),
    sexo character varying(255),
    CONSTRAINT animal_tb_aud_adotado_check CHECK (((adotado)::text = ANY ((ARRAY['DISPONIVEL'::character varying, 'ADOTADO'::character varying])::text[]))),
    CONSTRAINT animal_tb_aud_especie_check CHECK (((especie)::text = ANY ((ARRAY['GATO'::character varying, 'CACHORRO'::character varying])::text[]))),
    CONSTRAINT animal_tb_aud_maturidade_check CHECK (((maturidade)::text = ANY ((ARRAY['FILHOTE'::character varying, 'ADULTO'::character varying, 'IDOSO'::character varying])::text[]))),
    CONSTRAINT animal_tb_aud_origem_check CHECK (((origem)::text = ANY ((ARRAY['GUARDA_MUNICIPAL'::character varying, 'ABANDONO'::character varying, 'RESGATE'::character varying, 'SMA'::character varying, 'DIRETORIA'::character varying, 'COMUNIDADE'::character varying, 'FUNCIONARIO'::character varying, 'PORTAO'::character varying, 'OUTROS'::character varying])::text[]))),
    CONSTRAINT animal_tb_aud_porte_check CHECK (((porte)::text = ANY ((ARRAY['PEQUENO'::character varying, 'MEDIO'::character varying, 'GRANDE'::character varying])::text[]))),
    CONSTRAINT animal_tb_aud_saude_check CHECK (((saude)::text = ANY ((ARRAY['DOENTE'::character varying, 'SAUDAVEL'::character varying])::text[]))),
    CONSTRAINT animal_tb_aud_sexo_check CHECK (((sexo)::text = ANY ((ARRAY['MACHO'::character varying, 'FEMEA'::character varying])::text[])))
);


--
-- Name: animal_tb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.animal_tb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.animal_tb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: animal_tutores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.animal_tutores (
    animal_id bigint NOT NULL,
    tutor_id bigint NOT NULL
);


--
-- Name: animal_tutores_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.animal_tutores_aud (
    rev integer NOT NULL,
    revtype smallint,
    animal_id bigint NOT NULL,
    tutor_id bigint NOT NULL
);


--
-- Name: boletins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.boletins (
    arquivado boolean NOT NULL,
    arquivado_em timestamp(6) with time zone,
    atualizado_em timestamp(6) without time zone NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    data_atendimento timestamp(6) without time zone,
    id bigint NOT NULL,
    numero_ocorrencia bigint NOT NULL,
    ong_id bigint,
    arquivado_por character varying(100),
    motivo_arquivamento character varying(120),
    bairro character varying(255),
    cidade character varying(255),
    cpf_denunciante_ou_tutor character varying(255),
    destino character varying(255),
    estado character varying(255),
    motivo_recolhimento character varying(255),
    municipio character varying(255),
    nome_denunciante_ou_tutor character varying(255),
    observacao_clinica character varying(255),
    origem character varying(255),
    rua_avenida character varying(255),
    telefone_denunciante_ou_tutor character varying(255),
    CONSTRAINT boletins_destino_check CHECK (((destino)::text = ANY ((ARRAY['ABRIGO'::character varying, 'ADOTACAO'::character varying, 'DEVOLUCAO_TUTOR'::character varying, 'COMUNITARIO'::character varying, 'OUTRO'::character varying])::text[]))),
    CONSTRAINT boletins_origem_check CHECK (((origem)::text = ANY ((ARRAY['GUARDA_MUNICIPAL'::character varying, 'ABANDONO'::character varying, 'RESGATE'::character varying, 'SMA'::character varying, 'DIRETORIA'::character varying, 'COMUNIDADE'::character varying, 'FUNCIONARIO'::character varying, 'PORTAO'::character varying, 'OUTROS'::character varying])::text[])))
);


--
-- Name: boletins_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.boletins_aud (
    arquivado boolean,
    rev integer NOT NULL,
    revtype smallint,
    arquivado_em timestamp(6) with time zone,
    data_atendimento timestamp(6) without time zone,
    id bigint NOT NULL,
    numero_ocorrencia bigint,
    ong_id bigint,
    arquivado_por character varying(100),
    motivo_arquivamento character varying(120),
    bairro character varying(255),
    cidade character varying(255),
    cpf_denunciante_ou_tutor character varying(255),
    destino character varying(255),
    estado character varying(255),
    motivo_recolhimento character varying(255),
    municipio character varying(255),
    nome_denunciante_ou_tutor character varying(255),
    observacao_clinica character varying(255),
    origem character varying(255),
    rua_avenida character varying(255),
    telefone_denunciante_ou_tutor character varying(255),
    CONSTRAINT boletins_aud_destino_check CHECK (((destino)::text = ANY ((ARRAY['ABRIGO'::character varying, 'ADOTACAO'::character varying, 'DEVOLUCAO_TUTOR'::character varying, 'COMUNITARIO'::character varying, 'OUTRO'::character varying])::text[]))),
    CONSTRAINT boletins_aud_origem_check CHECK (((origem)::text = ANY ((ARRAY['GUARDA_MUNICIPAL'::character varying, 'ABANDONO'::character varying, 'RESGATE'::character varying, 'SMA'::character varying, 'DIRETORIA'::character varying, 'COMUNIDADE'::character varying, 'FUNCIONARIO'::character varying, 'PORTAO'::character varying, 'OUTROS'::character varying])::text[])))
);


--
-- Name: boletins_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.boletins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.boletins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categoria_estoque_tb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categoria_estoque_tb (
    atualizado_em timestamp(6) without time zone NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    estoque_id bigint NOT NULL,
    id bigint NOT NULL,
    descricao character varying(255),
    nome character varying(255) NOT NULL
);


--
-- Name: categoria_estoque_tb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categoria_estoque_tb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_estoque_tb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consumo_alimento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consumo_alimento (
    consumo_diario double precision NOT NULL,
    atualizado_em timestamp(6) without time zone NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    porte character varying(255) NOT NULL,
    CONSTRAINT consumo_alimento_porte_check CHECK (((porte)::text = ANY ((ARRAY['PEQUENO'::character varying, 'MEDIO'::character varying, 'GRANDE'::character varying])::text[])))
);


--
-- Name: consumo_alimento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.consumo_alimento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consumo_alimento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: despesas_tb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.despesas_tb (
    data_pagamento date,
    data_prevista_pagamento date,
    valor numeric(38,2) NOT NULL,
    atualizado_em timestamp(6) without time zone NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    ong_id bigint,
    categoria_despesa character varying(255),
    descricao character varying(255),
    forma_pagamento character varying(255),
    observacoes text,
    status_despesa character varying(255),
    CONSTRAINT despesas_tb_categoria_despesa_check CHECK (((categoria_despesa)::text = ANY ((ARRAY['ONG'::character varying, 'ANIMAL'::character varying, 'MEDICAMENTO'::character varying, 'RACAO'::character varying])::text[]))),
    CONSTRAINT despesas_tb_forma_pagamento_check CHECK (((forma_pagamento)::text = ANY ((ARRAY['CREDITO'::character varying, 'DEBITO'::character varying, 'PIX'::character varying, 'BOLETO'::character varying, 'OUTROS'::character varying])::text[]))),
    CONSTRAINT despesas_tb_status_despesa_check CHECK (((status_despesa)::text = ANY ((ARRAY['PENDENTE'::character varying, 'PAGO'::character varying, 'ATRASADA'::character varying])::text[])))
);


--
-- Name: despesas_tb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.despesas_tb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.despesas_tb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estoque_tb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estoque_tb (
    atualizado_em timestamp(6) without time zone NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    ong_id bigint NOT NULL,
    descricao character varying(255),
    nome character varying(255) NOT NULL
);


--
-- Name: estoque_tb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estoque_tb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estoque_tb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.media_file (
    archived boolean,
    has_thumb_large boolean,
    has_thumb_small boolean,
    height integer,
    width integer,
    id bigint NOT NULL,
    size_bytes bigint NOT NULL,
    uploaded_at timestamp(6) with time zone NOT NULL,
    checksum character varying(64),
    content_type character varying(128) NOT NULL,
    original_filename character varying(160),
    object_key character varying(512) NOT NULL
);


--
-- Name: media_file_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.media_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_link; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.media_link (
    sort_order integer,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    media_file_id bigint NOT NULL,
    target_id bigint NOT NULL,
    usage character varying(32) NOT NULL,
    target_type character varying(64) NOT NULL,
    CONSTRAINT media_link_usage_check CHECK (((usage)::text = ANY ((ARRAY['RESGATE'::character varying, 'GALERIA'::character varying, 'PERFIL'::character varying, 'EXAME'::character varying, 'LAUDO'::character varying, 'DOCUMENTO'::character varying])::text[])))
);


--
-- Name: media_link_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.media_link ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: obito_tb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.obito_tb (
    atualizado_em timestamp(6) without time zone NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    data_obito timestamp(6) without time zone,
    id bigint NOT NULL,
    motivo_obito character varying(255)
);


--
-- Name: obito_tb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.obito_tb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.obito_tb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ong_tb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ong_tb (
    atualizado_em timestamp(6) without time zone NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL
);


--
-- Name: ong_tb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ong_tb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ong_tb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.produto (
    preco numeric(10,2),
    quantidade double precision NOT NULL,
    atualizado_em timestamp(6) without time zone NOT NULL,
    categoria_estoque_id bigint NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    estoque_id bigint NOT NULL,
    id bigint NOT NULL,
    descricao character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    tipo_produto character varying(255),
    unidade_de_medida character varying(255) NOT NULL,
    CONSTRAINT produto_tipo_produto_check CHECK (((tipo_produto)::text = ANY ((ARRAY['RACAO'::character varying, 'ALIMENTACAO'::character varying, 'MEDICAMENTO'::character varying, 'HIGIENE'::character varying, 'LIMPEZA'::character varying, 'ACESSORIO'::character varying, 'BRINQUEDO'::character varying, 'UTENSILIOS'::character varying, 'OUTRO'::character varying])::text[]))),
    CONSTRAINT produto_unidade_de_medida_check CHECK (((unidade_de_medida)::text = ANY ((ARRAY['QUILO'::character varying, 'LITRO'::character varying, 'UNIDADE'::character varying, 'CAIXA'::character varying, 'ML'::character varying])::text[])))
);


--
-- Name: produto_atributos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.produto_atributos (
    produto_id bigint NOT NULL,
    atributo_chave character varying(255) NOT NULL,
    atributo_valor character varying(255)
);


--
-- Name: produto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.produto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: receitas_tb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.receitas_tb (
    data_recebimento date,
    valor numeric(38,2) NOT NULL,
    atualizado_em timestamp(6) without time zone NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    ong_id bigint,
    categoria character varying(255),
    descricao character varying(255) NOT NULL,
    forma_pagamento character varying(255),
    observacoes text,
    origem character varying(255),
    CONSTRAINT receitas_tb_forma_pagamento_check CHECK (((forma_pagamento)::text = ANY ((ARRAY['CREDITO'::character varying, 'DEBITO'::character varying, 'PIX'::character varying, 'BOLETO'::character varying, 'OUTROS'::character varying])::text[])))
);


--
-- Name: receitas_tb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.receitas_tb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.receitas_tb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recuperar_senha_tb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recuperar_senha_tb (
    atualizado_em timestamp(6) without time zone NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    expiracao_token timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    token character varying(255) NOT NULL
);


--
-- Name: recuperar_senha_tb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recuperar_senha_tb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recuperar_senha_tb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: revisao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.revisao (
    id integer NOT NULL,
    "timestamp" bigint NOT NULL,
    username character varying(255)
);


--
-- Name: revisao_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.revisao_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tutor_animal_tb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tutor_animal_tb (
    animal_id bigint NOT NULL,
    tutor_id bigint NOT NULL
);


--
-- Name: tutor_tb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tutor_tb (
    idade integer,
    atualizado_em timestamp(6) without time zone NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    id_ong bigint,
    bairro character varying(255),
    cep character varying(255),
    cidade character varying(255),
    cpf character varying(255),
    estado character varying(255),
    nome character varying(255),
    rua character varying(255),
    telefone character varying(255)
);


--
-- Name: tutor_tb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tutor_tb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tutor_tb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_tb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_tb (
    atualizado_em timestamp(6) without time zone NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    ong_id bigint,
    email character varying(255) NOT NULL,
    nome character varying(255),
    role character varying(255),
    senha character varying(255) NOT NULL,
    CONSTRAINT usuario_tb_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'COLABORADOR'::character varying])::text[])))
);


--
-- Name: usuario_tb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario_tb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_tb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activity_log activity_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_log
    ADD CONSTRAINT activity_log_pkey PRIMARY KEY (id);


--
-- Name: animal_conjunto_tb animal_conjunto_tb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_conjunto_tb
    ADD CONSTRAINT animal_conjunto_tb_pkey PRIMARY KEY (animal_conjunto_id);


--
-- Name: animal_doencas_aud animal_doencas_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_doencas_aud
    ADD CONSTRAINT animal_doencas_aud_pkey PRIMARY KEY (rev, animal_id, doenca);


--
-- Name: animal_tb_aud animal_tb_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_tb_aud
    ADD CONSTRAINT animal_tb_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: animal_tb animal_tb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_tb
    ADD CONSTRAINT animal_tb_pkey PRIMARY KEY (id);


--
-- Name: animal_tutores_aud animal_tutores_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_tutores_aud
    ADD CONSTRAINT animal_tutores_aud_pkey PRIMARY KEY (rev, animal_id, tutor_id);


--
-- Name: animal_tutores animal_tutores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_tutores
    ADD CONSTRAINT animal_tutores_pkey PRIMARY KEY (animal_id, tutor_id);


--
-- Name: boletins_aud boletins_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boletins_aud
    ADD CONSTRAINT boletins_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: boletins boletins_numero_ocorrencia_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boletins
    ADD CONSTRAINT boletins_numero_ocorrencia_key UNIQUE (numero_ocorrencia);


--
-- Name: boletins boletins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boletins
    ADD CONSTRAINT boletins_pkey PRIMARY KEY (id);


--
-- Name: categoria_estoque_tb categoria_estoque_tb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria_estoque_tb
    ADD CONSTRAINT categoria_estoque_tb_pkey PRIMARY KEY (id);


--
-- Name: consumo_alimento consumo_alimento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consumo_alimento
    ADD CONSTRAINT consumo_alimento_pkey PRIMARY KEY (id);


--
-- Name: despesas_tb despesas_tb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.despesas_tb
    ADD CONSTRAINT despesas_tb_pkey PRIMARY KEY (id);


--
-- Name: estoque_tb estoque_tb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estoque_tb
    ADD CONSTRAINT estoque_tb_pkey PRIMARY KEY (id);


--
-- Name: media_file media_file_object_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_file
    ADD CONSTRAINT media_file_object_key_key UNIQUE (object_key);


--
-- Name: media_file media_file_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_file
    ADD CONSTRAINT media_file_pkey PRIMARY KEY (id);


--
-- Name: media_link media_link_media_file_id_target_type_target_id_usage_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_link
    ADD CONSTRAINT media_link_media_file_id_target_type_target_id_usage_key UNIQUE (media_file_id, target_type, target_id, usage);


--
-- Name: media_link media_link_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_link
    ADD CONSTRAINT media_link_pkey PRIMARY KEY (id);


--
-- Name: obito_tb obito_tb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obito_tb
    ADD CONSTRAINT obito_tb_pkey PRIMARY KEY (id);


--
-- Name: ong_tb ong_tb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ong_tb
    ADD CONSTRAINT ong_tb_pkey PRIMARY KEY (id);


--
-- Name: produto_atributos produto_atributos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produto_atributos
    ADD CONSTRAINT produto_atributos_pkey PRIMARY KEY (produto_id, atributo_chave);


--
-- Name: produto produto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT produto_pkey PRIMARY KEY (id);


--
-- Name: receitas_tb receitas_tb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receitas_tb
    ADD CONSTRAINT receitas_tb_pkey PRIMARY KEY (id);


--
-- Name: recuperar_senha_tb recuperar_senha_tb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recuperar_senha_tb
    ADD CONSTRAINT recuperar_senha_tb_pkey PRIMARY KEY (id);


--
-- Name: revisao revisao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.revisao
    ADD CONSTRAINT revisao_pkey PRIMARY KEY (id);


--
-- Name: tutor_animal_tb tutor_animal_tb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutor_animal_tb
    ADD CONSTRAINT tutor_animal_tb_pkey PRIMARY KEY (animal_id, tutor_id);


--
-- Name: tutor_tb tutor_tb_cpf_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutor_tb
    ADD CONSTRAINT tutor_tb_cpf_key UNIQUE (cpf);


--
-- Name: tutor_tb tutor_tb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutor_tb
    ADD CONSTRAINT tutor_tb_pkey PRIMARY KEY (id);


--
-- Name: boletins uk_boletins_numero_ocorrencia; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boletins
    ADD CONSTRAINT uk_boletins_numero_ocorrencia UNIQUE (numero_ocorrencia);


--
-- Name: categoria_estoque_tb uk_categoria_por_estoque_nome; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria_estoque_tb
    ADD CONSTRAINT uk_categoria_por_estoque_nome UNIQUE (estoque_id, nome);


--
-- Name: media_link ukj6offbm7lqcm9gq82x8jd3a3m; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_link
    ADD CONSTRAINT ukj6offbm7lqcm9gq82x8jd3a3m UNIQUE (media_file_id, target_type, target_id, usage);


--
-- Name: animal_tb unique_chip_id_when_not_null; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_tb
    ADD CONSTRAINT unique_chip_id_when_not_null UNIQUE (chip_id);


--
-- Name: usuario_tb usuario_tb_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_tb
    ADD CONSTRAINT usuario_tb_email_key UNIQUE (email);


--
-- Name: usuario_tb usuario_tb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_tb
    ADD CONSTRAINT usuario_tb_pkey PRIMARY KEY (id);


--
-- Name: produto_atributos fk2oitsdumhd0tapryfn3avd5o4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produto_atributos
    ADD CONSTRAINT fk2oitsdumhd0tapryfn3avd5o4 FOREIGN KEY (produto_id) REFERENCES public.produto(id);


--
-- Name: boletins_aud fk2x4ijs88vexylfkht95tgd0fg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boletins_aud
    ADD CONSTRAINT fk2x4ijs88vexylfkht95tgd0fg FOREIGN KEY (rev) REFERENCES public.revisao(id);


--
-- Name: tutor_animal_tb fk4sl0l6cha3fnrjqnjastjr5hj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutor_animal_tb
    ADD CONSTRAINT fk4sl0l6cha3fnrjqnjastjr5hj FOREIGN KEY (animal_id) REFERENCES public.animal_tb(id);


--
-- Name: despesas_tb fk4wyo1pwrpv33idoxn137eddcg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.despesas_tb
    ADD CONSTRAINT fk4wyo1pwrpv33idoxn137eddcg FOREIGN KEY (ong_id) REFERENCES public.ong_tb(id);


--
-- Name: animal_tb_aud fk5whq9em400j2w0hokppqe8905; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_tb_aud
    ADD CONSTRAINT fk5whq9em400j2w0hokppqe8905 FOREIGN KEY (rev) REFERENCES public.revisao(id);


--
-- Name: animal_tb fk6wgifudjmy1fxrkx33ab2kogm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_tb
    ADD CONSTRAINT fk6wgifudjmy1fxrkx33ab2kogm FOREIGN KEY (id_ong) REFERENCES public.ong_tb(id);


--
-- Name: receitas_tb fk9iahjtf9w9kc705qmevfh9jut; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receitas_tb
    ADD CONSTRAINT fk9iahjtf9w9kc705qmevfh9jut FOREIGN KEY (ong_id) REFERENCES public.ong_tb(id);


--
-- Name: animal_tb fk_animal_boletim; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_tb
    ADD CONSTRAINT fk_animal_boletim FOREIGN KEY (boletim_id) REFERENCES public.boletins(id);


--
-- Name: animal_tutores_aud fkaxf06cjbsbfsxpk809gte3gi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_tutores_aud
    ADD CONSTRAINT fkaxf06cjbsbfsxpk809gte3gi FOREIGN KEY (rev) REFERENCES public.revisao(id);


--
-- Name: produto fkb3oeo3uwsxtkv4h9yvhbyxyi4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT fkb3oeo3uwsxtkv4h9yvhbyxyi4 FOREIGN KEY (categoria_estoque_id) REFERENCES public.categoria_estoque_tb(id);


--
-- Name: media_link fkbsbq3dmqh3fw0euen8qt8nhxd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_link
    ADD CONSTRAINT fkbsbq3dmqh3fw0euen8qt8nhxd FOREIGN KEY (media_file_id) REFERENCES public.media_file(id);


--
-- Name: usuario_tb fkgl89ju7edap4jtqfoyea2w5xg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_tb
    ADD CONSTRAINT fkgl89ju7edap4jtqfoyea2w5xg FOREIGN KEY (ong_id) REFERENCES public.ong_tb(id);


--
-- Name: animal_tutores fkh4hbj10xghja8lfljdj1pue71; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_tutores
    ADD CONSTRAINT fkh4hbj10xghja8lfljdj1pue71 FOREIGN KEY (animal_id) REFERENCES public.animal_tb(id);


--
-- Name: tutor_tb fkhfaga72mwgoa0y06fq0c8n21j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutor_tb
    ADD CONSTRAINT fkhfaga72mwgoa0y06fq0c8n21j FOREIGN KEY (id_ong) REFERENCES public.ong_tb(id);


--
-- Name: animal_tutores fkhrsmpcvklyemswwmuc9de90hc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_tutores
    ADD CONSTRAINT fkhrsmpcvklyemswwmuc9de90hc FOREIGN KEY (tutor_id) REFERENCES public.tutor_tb(id);


--
-- Name: animal_doencas_aud fkibfmcipc8vsct2nvoaxudv6oa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_doencas_aud
    ADD CONSTRAINT fkibfmcipc8vsct2nvoaxudv6oa FOREIGN KEY (rev) REFERENCES public.revisao(id);


--
-- Name: tutor_animal_tb fkiifc63mla1okihobu2dg26ckt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutor_animal_tb
    ADD CONSTRAINT fkiifc63mla1okihobu2dg26ckt FOREIGN KEY (tutor_id) REFERENCES public.tutor_tb(id);


--
-- Name: animal_doencas fkkq486q2rdt6ssrfuk7321kgi8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_doencas
    ADD CONSTRAINT fkkq486q2rdt6ssrfuk7321kgi8 FOREIGN KEY (animal_id) REFERENCES public.animal_tb(id);


--
-- Name: animal_conjunto_tb fkm49xyuxjworjle3sirbs0mdt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_conjunto_tb
    ADD CONSTRAINT fkm49xyuxjworjle3sirbs0mdt FOREIGN KEY (animal_principal_id) REFERENCES public.animal_tb(id);


--
-- Name: boletins fkoo054nupeolyv8m7qrn7aksg6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boletins
    ADD CONSTRAINT fkoo054nupeolyv8m7qrn7aksg6 FOREIGN KEY (ong_id) REFERENCES public.ong_tb(id);


--
-- Name: produto fkq5vpwjlf5j8t7oafe0g99lbov; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT fkq5vpwjlf5j8t7oafe0g99lbov FOREIGN KEY (estoque_id) REFERENCES public.estoque_tb(id);


--
-- Name: animal_conjunto_tb fkqge81x7kv1vwmvnfk7d81mp3p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_conjunto_tb
    ADD CONSTRAINT fkqge81x7kv1vwmvnfk7d81mp3p FOREIGN KEY (animal_relacionamento_id) REFERENCES public.animal_tb(id);


--
-- Name: estoque_tb fkqvol9hrqpdlhl0o4ow0bsxubw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estoque_tb
    ADD CONSTRAINT fkqvol9hrqpdlhl0o4ow0bsxubw FOREIGN KEY (ong_id) REFERENCES public.ong_tb(id);


--
-- Name: categoria_estoque_tb fkrv988htb3td0ihjafilr6olf1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria_estoque_tb
    ADD CONSTRAINT fkrv988htb3td0ihjafilr6olf1 FOREIGN KEY (estoque_id) REFERENCES public.estoque_tb(id);


--
-- PostgreSQL database dump complete
--


